source "https://rubygems.org"
ruby '1.9.3'

def darwin_only(require_as)
  RUBY_PLATFORM.include?('darwin') && require_as
end

def linux_only(require_as)
  RUBY_PLATFORM.include?('linux') && require_as
end

group :test do
  gem 'rake', '~> 10.1.0'
  gem 'puppet-lint', "~> 0.3.2"
  gem 'rspec-puppet'
  puppetversion = ENV.key?('PUPPET_VERSION') ? "~> #{ENV['PUPPET_VERSION']}" : ['>= 2.7']
  gem 'puppet', puppetversion
  gem 'puppetlabs_spec_helper'
  gem 'beaker'
end
